language: node_js
node_js:
- '7.9'

sudo:
  required

cache:
  yarn: true

before-script:
- yarn add grunt
- yarn add grunt-cli
- yarn add typescript
- yarn add grunt-ts
- yarn install

script:
- grunt travis

after_success:
- bash post_build.sh

after_failure:
- cat client/l4w.js

env:
  global:
    secure: "Pf+LRnh6VY3/dz6Xll43yrm8U5U5h7UNCB5hN09EtAf0V8ebbJx9qBvfcutYsQWrJq0Lb9+T7oT354c6saSAMXRqu5SkMLNBeuMGwHUdBc10Ew0i6K8FL/itoezguAT7LN/T2ziSmkiddlOFikoAqrWYOQig52ZoEoVF7z4HQv5ZuceyYZkfOMKR0stj9Kr3mmXS2RsRnfNxIzcx66sqCCsaGMqrH3+x1r3Lnv7MKbvBHGDDKfuItNAUkyTl/ELd3X80GC694Oj3L3lW/7rnvld4CdgLJW5RdKTIN7Clu48Dps85u6zcL/lpRyQLcmO44A8JwxlmUEOg7HslgQITF+c74dohFk+vW+Y6tUUErEGtfZnG0d0MDMBX5su2WS6SrOQ37DTnhI5KQpB/ShVKyF+NNMXBrThj40ZXFZhg76Wu6gZW2YfbyuvYnceTGbHVhmXvyYXuqn0mHa22GiyFCQGUwhJWriV3k0yXkiegRwYQbOZxs6ssiRoRnRBcXwuPyzlXzXnoXjIeU2Fub0WA4sWtXYJxeM+uzzg9iFfDe4QeiffBre3BP3pK6FMxeekGioOS7CHAVdrO0ZLlIRBbGjJscSit+cRiyc3jedcOtqeQ6OTovnF9mkVEaofHbkU7NyH3yZJddCTev6XVXFrzdNOYWBf0S0+1P8GrwzcIOiU="

notifications:
  email: false
