language: node_js
node_js:
- '0.12'
install:
- npm install grunt-cli -g
- npm install
script:
- grunt travis
after_success:
- bash post_build.sh
env:
  global:
    secure: K7YYY8fOnDhz+GeUJKvAGpzSTG+2l55wnYcTtr9AawPEnk89W5PUpIxithz27k9PDjS5tnSLOfoDV9cDO+UanHf0nyh8RMCVxCbz319t7fdt7Wmw3z2yKyvYpQ0ai69yUJBxtVvnLccxT0THzI63Sl7fhIqOerT2VB0blp9YoMYBjkWEIlg06tb7Gjp0642HKHCb69eYODXNAYeQ+7roaZL/3SESt0n66S6Pu9DYxwc3H+wRATaFVQ1vCrUysyo871IA/NBEn32sq5rxtS0PyDFb3p5nKRPfLK8Zhv805dQTvT/Ubp+lHxYiEhHZwnAUFcdyLWFwm84ObN09fkZ/lK2mT356Bl9pz/4HcZsI1jwy3hREJiQcc8ZEdsLZzhRwHqemzaDNjCAw/93wnJzGn0SFb4AjAiUftIREW8kLKLW1NukyfNAo9TnRAeoc6VxQNKT05xInChoE4ZFcvzmrs+nFK19Foaiyp5STQZpgBJjnKQb7PQVL49Pj6+8KOTZHUKdo3VKRym5uAW8lKJOogYS+GVw5CihPYmueTak5EcPPfCpWbwnCrhStV2YSmzMUZ2xJaJYpyFDf3YVg9M5LbtR5FGWvMC/FT0cptbBCTiP88XzY8HSwfpV31jt22h8/fA6SYEW9bZHekRmEHONjn4Piaj/3YRdqAffrzcetMsg=
