language: node_js
node_js:
- '0.12'
install:
- npm install grunt-cli -g
- npm install
script:
- grunt travis
after_success:
- gem install heroku
deploy:
  provider: heroku
  api_key:
    secure: ERCv7f8EuQ91T0g0I3FhOWF1EzcHqDm8b2Ivi9W6jyQeW7F9Pdv5++377mv1F+l/yVBZMk7cTfIkRE0gFpy5VCdtpV9VHItVY37bprB+JHb3RLqCe3m2DUEHXoDgYlAKQP4Tsd7QYvK3DwgqX4oOjmGQ+SFlcPRL8EGUwV5zFdNzVMZBVuSgUwlX0YajxH+I/dAggU7Z2P/L14+5frCQEoa3u6Id1fbiGD0WCEabz0bxISvadgYAh6lLW77Kvij9M84c511xDzBMuO90REOwLFHQjov4/Ui+Wh+uNzeL7vdQ/spgm4zP1vUrg5fP4qVFxjHOYw7gJxretbPD1Z4S+0/up0DXnZ32tHq6DGFLKLDys/j3sSxfxUFuj+GhpSQCu4cdXEWhUTM47H5nSvx8CCXMDvm9RVlH1a6lNbgpbNVN59FiR7x26+NrKQOubDbDvAFEVPSwnt3Ky5k5miSGGhU8Y6PlTDUHMlT5en2hdjEg+0qHiuMpY62JATpp9CcbK48SYuqj3DnALAfEfKbIttH3qiJiOjITh3sRcDD8P3xsyEMXy93NniWty0BOa8Bpg+OFMo4cqdG6fOYs0cT9UqNawbRNt8Yk4KZNXA94/19iHHog7ZB4pH2vw5BezzdoWnME3t59fxszZIzdFrWplRX4d7tiCq58FU+sEBVLPbQ=
  skip_cleanup: true
  strategy: git
