language: node_js
node_js:
- '7.9'

sudo:
  required

cache:
  yarn: true

before-script:
- yarn add grunt
- yarn add grunt-cli
- yarn add typescript
- yarn add grunt-ts
- yarn install

script:
- grunt travis

after_success:
- bash post_build.sh

after_failure:
- cat client/l4w.js

env:
  global:
    secure: "atZ38eGbLQfbkAcdPctT7s6Z/Fv4g7pkP+s6CZGrO3y4xjgq4XE11WPo2wrpuCnsUQAvLa+SqujSmiS4779QlbdZRmVTvlnBj/gYMq+m8KSqdw9JVPk48dmzqco76YI3/xbryVGX3g0LRHGhaYxZ2V1diYsUT0a67RVTEAij+1nR2R1tu+q1Tx+FSRbRzXh7ExgydZjBSY+cn3+66LbuCnATn6DrktZqbskdN9tbt3Lzs7BGk7fuDHYwgussSxs+7yzwAxoxzDrvDJAO00Z0NvcsHhe3PXC+sKXewrZHqXBwx4IUkScLdqk4D80wSsDwPmFoAp9WUSCAzRMVC82AwTHPGoR2C7c50iidr3g7CH410qo8cHPo4kX3bUKJK12RWygDa87nBuaOfAF077qUz3M/bf3+nlIhG8IzjMS2vDIcVaCeNR5nvb3+Uksd3/4l7kghN2PNv86bydgaXWfk1C7japU+WntINQUhQZ3AUI/9Pc9gBw0/imnnpbMreQ5q7kfHMdHldnEKWPH6EOizX8D+cAfWA37O3UDYQKozZQl7UkP3mcK4FMT0I9oXA+t83Zp5C+wjtTVquJmy1aqFoviJrApc2sz/ZcJRVS3gbhlLTs7ZDllUHtVjgwVdlDUoLEuRYg1+IIrx/kZXtm62voDb+7g792+fbm2kCRocsWE="

notifications:
  email: false
