language: node_js
node_js:
- '0.12'
install:
- npm install grunt-cli -g
- npm install
script:
- grunt travis
after_success: 
deploy:
  provider: releases
  api_key:
    secure: TldI9PhDi4gw/oHgqrs/1NwNRY0aTsEFdux9Yl/D1p+81gxt5anQR7Ohd0AeQ2rxwxpXrw2hmLjLrcXn5iBqBxj1BY4J75KOpdvHqLON2yFRAvbQgbnpoe6vokACZp0mLxKz6yb09cH7k+8XJvZZualrkA+ipfD6Xt41O9HbMdUCbjwo54sCGzucDUc75j2Gl/59upHSXoSdCRCrXhS1+ZXl+54HM7WifZ/nH/RFo3xTuRMziFni3W02HwyRGZusUYvx3Taf1tUe7pZ400DM5eiEB6ZVzIfSUxA3y1B572DcvB2MCFdsY6bylgcc/57B49iwUR2tRySvZp99YHYkShIhaLForBCp4jiWAsTS5cY56bVCIs413B5XUfR6acYo3j1c/AlQLTbhi1Qu2Seh3Qg1HymAzUFPQKuAs+9sj1xJgjIlFXPmo7HnYKJvOXrlYCIbz1F7JVnHYoOe+otwXKBlH/BNx4tWTZkKlpHF6hG/HTrIBXJgx61bMX+odkfW5+w6C+/pmAxM+FKeuKLCpGO04ZgMGxIBKCzl14Qj9dIQVZwrERrCViVKR1d/hU921X5miUj/siFg0gz5yLEIs6w6KYDp12i6T9bu2TIt4clLFJW0PNK9MUwOvHLLN6Z3rfK7ySW0Job5klM7fTGobfkN+9jojWZ4Z9ttQX0uwKs=
  file:
  - "client/l4w.js"
  - "client/l4w.min.js"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true